# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c3846c2ed61c363bab9b7c060e1ec5c2"
name = "Brad NextGen COD"
handle = "brad-nextgen-cod"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "bradnextgencod.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_orders,write_checkouts,write_orders"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
